import{a as w,S as x,i as u}from"./assets/vendor-LKfbwt14.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))d(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const n of s.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&d(n)}).observe(document,{childList:!0,subtree:!0});function c(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function d(e){if(e.ep)return;e.ep=!0;const s=c(e);fetch(e.href,s)}})();const S="47506069-50a24acca197abc732faaa7f2";async function h(a,r=1){return(await w("https://pixabay.com/api/",{params:{key:S,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15}})).data}function g(a){return a.map(({largeImageURL:c,webformatURL:d,likes:e,views:s,comments:n,downloads:L,id:b,tags:v})=>`<li class="gallery-card" data-id="${b}">
      <a class="gallery-link" href="${c}">
  <img class="pixabay-img" src="${d}" alt="${v}" width="360" height="160"/>
  </a>
  <div class="wrapper-card-text">
  <p class="card-text">Likes <span>${e}</span></p>
   <p class="card-text">Views <span>${s}</span></p>
    <p class="card-text">Comments <span>${n}</span></p>
     <p class="card-text">Downloads <span>${L}</span></p>
  </div>
  </li>`).join("")}function f(){return new x(".gallery a",{captionsData:"alt",captionDelay:"250",className:"wrapper"}).refresh()}function q(){return u.show({theme:"dark",iconUrl:"../img/icons/alert.svg",imageWidth:"24px",position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#fff",messageSize:"16px",messageLineHeight:"24px",backgroundColor:"#EF4040",timeout:5e3,displayMode:1})}function y(){return u.show({theme:"dark",iconUrl:"../img/icons/alert.svg",imageWidth:"24px",position:"topRight",message:" We are sorry, but you have reached the end of search results.",messageColor:"#fff",messageSize:"16px",messageLineHeight:"24px",backgroundColor:"#EF4040",timeout:5e3,displayMode:1})}const E=document.querySelector(".form-search-img"),p=document.querySelector(".gallery"),t=document.querySelector(".load-more-btn"),o=document.querySelector(".loader-is-hidden");let i=1,l,m;E.addEventListener("submit",P);async function P(a){if(a.preventDefault(),o.classList.replace("loader-is-hidden","loader"),t.classList.remove("load-more-visible"),i=1,m=a.target.elements.titleImage.value.trim(),!!m){p.innerHTML="";try{const r=await h(m,i);if(o.classList.replace("loader","loader-is-hidden"),r.hits.length===0)throw o.classList.replace("loader","loader-is-hidden"),new Error("There are no images matching your search query");if(l=Math.ceil(r.totalHits/15),i>l)throw o.classList.replace("loader","loader-is-hidden"),new Error("Ran out of pictures");p.insertAdjacentHTML("beforeend",g(r.hits)),f(),t.classList.add("load-more-visible"),i===l&&t.classList.remove("load-more-visible")}catch(r){o.classList.replace("loader","loader-is-hidden"),t.classList.remove("load-more-visible"),r.message=="There are no images matching your search query"?q():r.message=="Ran out of pictures"&&y()}finally{a.target.elements.titleImage.value=""}}}t.addEventListener("click",async()=>{try{t.classList.remove("load-more-visible"),o.classList.replace("loader-is-hidden","loader"),i+=1;const a=await h(m,i);if(o.classList.replace("loader","loader-is-hidden"),t.classList.add("load-more-visible"),l=Math.ceil(a.totalHits/15),i>l)throw t.classList.remove("load-more-visible"),new Error;p.insertAdjacentHTML("beforeend",g(a.hits)),f();const c=document.querySelector(".gallery-card").getBoundingClientRect().height;if(window.scrollBy({left:0,top:c*2,behavior:"smooth"}),t.classList.add("load-more-visible"),i===l)throw t.classList.remove("load-more-visible"),new Error("The last page")}catch(a){if(o.classList.replace("loader","loader-is-hidden"),t.classList.remove("load-more-visible"),i>l||a.message==="The last page")return y()}});
//# sourceMappingURL=index.js.map
