import{a as b,S as x,i as u}from"./assets/vendor-LKfbwt14.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const L="47506069-50a24acca197abc732faaa7f2";async function p(a,t){m.insertAdjacentHTML("afterbegin",'<div class="loader" ></div>');const o=document.querySelector(".loader"),s=await b("https://pixabay.com/api/",{params:{key:L,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}});return o.remove(),s.data}function g(a){return a.map(({largeImageURL:o,webformatURL:s,likes:e,views:r,comments:c,downloads:h,id:y,tags:v})=>`<li class="gallery-card" data-id="${y}">
      <a class="gallery-link" href="${o}">
  <img class="pixabay-img" src="${s}" alt="${v}" width="360" height="160"/>
  </a>
  <div class="wrapper-card-text">
  <p class="card-text">Likes <span>${e}</span></p>
   <p class="card-text">Views <span>${r}</span></p>
    <p class="card-text">Comments <span>${c}</span></p>
     <p class="card-text">Downloads <span>${h}</span></p>
  </div>
  </li>`).join("")}function f(){return new x(".gallery a",{captionsData:"alt",captionDelay:"250",className:"wrapper"}).refresh()}function w(){return u.show({theme:"dark",iconUrl:"../img/icons/alert.svg",imageWidth:"24px",position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#fff",messageSize:"16px",messageLineHeight:"24px",backgroundColor:"#EF4040",timeout:5e3,displayMode:1})}function S(){return u.show({theme:"dark",iconUrl:"../img/icons/alert.svg",imageWidth:"24px",position:"topRight",message:" We are sorry, but you have reached the end of search results.",messageColor:"#fff",messageSize:"16px",messageLineHeight:"24px",backgroundColor:"#EF4040",timeout:5e3,displayMode:1})}const P=document.querySelector(".form-search-img"),m=document.querySelector(".gallery"),n=document.querySelector(".load-more-btn");let i=1,d,l;P.addEventListener("submit",q);async function q(a){if(a.preventDefault(),n.classList.remove("load-more-visible"),i=1,l=a.target.elements.titleImage.value.trim(),!!l)try{const t=await p(l,i);if(t.hits.length===0)throw new Error;m.insertAdjacentHTML("beforeend",g(t.hits)),f(),n.classList.add("load-more-visible")}catch{n.classList.remove("load-more-visible"),w()}finally{a.target.elements.titleImage.value=""}}const M=document.querySelector(".gallery-card");n.addEventListener("click",async()=>{try{n.insertAdjacentHTML("afterend",'<div class="loader" ></div>');const a=document.querySelector(".loader");i+=1;const t=await p(l,i);if(a.remove(),d=Math.ceil(t.totalHits/15),i>d)throw new Error;m.insertAdjacentHTML("beforeend",g(t.hits)),f();const o=M.getBoundingClientRect();window.scrollBy({left:0,top:o*2,behavior:"smooth"})}catch{if(i>d)return loader.remove(),n.classList.remove("load-more-visible"),S()}});
//# sourceMappingURL=index.js.map
